services:
  # The bookroom web.
  bookroom_web:
    build: .
    volumes:
      # - ./docker/volumes/app/bookroom-api/uploads:/usr/share/nginx/html/uploads
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
      #- ./docker/nginx/ssl:/etc/ssl
      - ./docker/entrypoint.sh:/entrypoint.sh:ro
    env_file:
      - .env.local
    ports:
      - "${EXPOSE_PORT:-80}:${PORT:-80}"
      - "${EXPOSE_SSL_PORT:-443}:${SSL_PORT:-443}"
    entrypoint: [ "/bin/bash", "/entrypoint.sh" ]
    restart: unless-stopped
